### PR TITLE
Update docs to reflect new behavior of Postgres source

### PR DESCRIPTION
**Pull request by nharring-adjacent**
Update user docs to reflect new behavior of Postgres replication source with respect to upstream table schemas, `ALTER TABLE` and  `CREATE VIEWS`.
### Motivation

  * This PR fixes a recognized bug: #6739

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

### CODE REVIEW

**Comment by morsapaes** [comment]
One thing I'm struggling with here is that these changes swing things again towards the old behaviour of the source (_i.e._ before the single materialization requiremen, where the source was materialized by default). Am I missing something?

**Comment by nharring-adjacent** [comment]
This is a really good question and I do not have a clear answer yet, I will do some testing to make sure I have a clear understanding of how things behave when creating a non-materialized postgres source since the issue that prompted this development was filed before that change you reference.

**Comment by nharring-adjacent** [comment]
I am going to close this and rebase it now that the implementation PR has merged, I will also verify that this behavior does not change anything with unmaterialized postgres sources and only takes effect when the source becomes materialized.

**Comment by nharring-adjacent** [comment]
Rereading that PR and the issue it was addressing I don't think this is a meaningful behavioral regression, the limitations being enforced around Postgres sources "should" have always existed since otherwise there were cases that could lead to correctness issues. One thing I need to clarify in these docs before I open a proper PR is that there is nothing being done "at source materialization time" but rather the snapshots all happen at source creation time regardless of when a materialized view might be created on top of it.

**Pull request closed without merging**
